name = "debt-payoff-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "FINANCE_DB"
database_name = "financeos-db"
database_id = "91df5ac9-1a79-4207-8551-4f53e9d6bec7"

[vars]
ENVIRONMENT = "production"
